### ISSUE TITLE
Eksepsi

### ISSUE THREAD

**Issue by quantro** [SymfonyId/SIABSkeleton#2]
Maaf kalau bukan tempat yang benar untuk tanya, saat mau instal...

>>[Symfony\Component\Config\Definition\Exception\InvalidTypeException] Invalid type for path "symfonian_indonesia_admin.filter". Expected array, but got string

>Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handl
ing the post-install-cmd event terminated with an exception

>>[RuntimeException]An error occurred when executing the ""cache:clear --no-warmup"" command.

**Comment by ihsanudin** [comment]
Coba composer update trus rubah bagian config filter : 'name' jadi ['name']

**Comment by quantro** [comment]
Seperti yang disarankan :
>Command: composer update

>>Loading composer repositories with package information 
>>Updating dependencies (including require-dev)
>>Generating autoload files
>>Updating the "app/config/parameters.yml" file
>>>[Symfony\Component\Config\Definition\Exception\InvalidTypeException] 
>>>Invalid type for path "symfonian_indonesia_admin.filter". Expected array, but got string

>>Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handl ing the post-update-cmd event terminated with an exception
>>>[RuntimeException]
>>>An error occurred when executing the ""cache:clear --no-warmup"" command.

config filter belum saya lakukan karena error ini :smile:

**Comment by ihsanudin** [comment]
Ini pakai SIAB Skeleton ataukah SIAB doank?

**Comment by ihsanudin** [comment]
Kalau SIAB Skeleton tinggal di config aja di AppBundle/Resources/config/config.yml

**Comment by ihsanudin** [comment]
@quantro : silahkan update vendor gan :-)

**Comment by quantro** [comment]
jadi saya ulang install dari awal... 
>composer create-project symfonyid/siab-skeleton SIAB 1.0.11
Installing symfonyid/siab-skeleton (1.0.11)
  - Installing symfonyid/siab-skeleton (1.0.11)
-Loading from cache
-Created project in SIAB
-Loading composer repositories with package information
-Installing dependencies (including require-dev)
-....
 
ada ini 

>  - Installing friendsofsymfony/user-bundle (dev-master 808672b)
    Cloning 808672b01f6aa6777417551c72a0be2c3545eafe
    Failed to download friendsofsymfony/user-bundle from source: The process "gi t clone --no-checkout "git://github.com/FriendsOfSymfony/FOSUserBundle.git" "D:\xampp\htdocs\symfony\SIAB\vendor\friendsofsymfony\user-bundle" && cd /D "D:\xampp\htdocs\symfony\SIAB\vendor\friendsofsymfony\user-bundle" && git remote add composer "git://github.com/FriendsOfSymfony/FOSUserBundle.git" && git fetch composer" exceeded the timeout of 300 seconds.
- Now trying to download from dist
  - Installing friendsofsymfony/user-bundle (dev-master 808672b)
    Downloading: 100%

Setelah input token muncul

>>[Symfony\Component\Config\Definition\Exception\InvalidTypeException] Invalid type for path "symfonian_indonesia_admin.filter". Expected array, but got string

>Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the post-install-cmd event terminated with an exception

>>[RuntimeException]
  An error occurred when executing the ""cache:clear --no-warmup"" command.

itu kenapa?

Env : 
Windows 8, xampp 3.2.1, php 5.4.22, mysql 5.5.34

**Comment by ihsanudin** [comment]
Coba update vendor gan... pake composer update

**Comment by ihsanudin** [comment]
Pastikan install latest 1.0.12 :-) bukan 11 lagi... maaf belum update

**Comment by quantro** [comment]
saya coba lagi install **fresh** :smile_cat: 
and this what happen....
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
D:\xampp\htdocs\symfony>composer create-project symfonyid/siab-skeleton SIAB 1.0.13
Installing symfonyid/siab-skeleton (1.0.13)
  - Installing symfonyid/siab-skeleton (1.0.13)
    Downloading: 100%

Created project in SIAB
Loading composer repositories with package information
Installing dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for symfonyid/admin-bundle dev-master -> satisfiable
by symfonyid/admin-bundle[dev-master].
    - symfonyid/admin-bundle dev-master requires friendsofsymfony/user-bundle ~2
.0@dev -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your min
imum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by ihsanudin** [comment]
@quantro : coba di composer.json di root folder SIAB (hasil download) tambahkan line ini:

``"friendsofsymfony/user-bundle": "~2.0@dev"``

Sepertinya itu karena composer-nya yang ga bisa download dependencies secara otomatis

**Comment by ihsanudin** [comment]
Bisa juga install ulang versi revisi 1.1 (udah di include manual fosub-nya)

**Comment by quantro** [comment]
alhamdulillah keinstall
tapi pas mau login n masukin user n pass gini 
![siab-login](http://i.imgur.com/obFXM3O.png?1)

and btw, saya install db bukan pake
>php app/console doctrine:schema:install

tapi 
>php app/console doctrine:schema:create

**Comment by ihsanudin** [comment]
:D Alhamdulillah... Ga masalah pake schema:create pun gpp yang penting setelah itu di dumb fixturesnya

Silahkan ikuti langkahnya di readme
